### ISSUE TITLE
On the VTUAV dataset training problem.

### ISSUE THREAD

**Issue by bxkzcb** [RyanHTR/TBSI#15]
Hello Recently I have followed this work of yours, it is very researchable, but I have some questions about the VTUAV dataset training issue , you describe in the paper that “For the VTUAV dataset, we train the model on the entire dataset and evaluate its effectiveness on the long-term and short-term test sets, respectively.” My question is, does “the entire dataset” include all the data in the training and test sets? I am looking forward to your reply, thank you.

**Comment by 981410121** [comment]
> 你好 最近我一直在关注你的这项工作，很有研究价值，但我对 VTUAV 数据集训练问题有一些疑问，你在论文中描述“对于 VTUAV 数据集，我们在整个数据集上训练模型，并分别在长期和短期测试集上评估其有效性”。我的问题是，“整个数据集”是否包括训练和测试集中的所有数据？期待您的回复，谢谢。

你好，你可以在VTUAV训练吗？

**Comment by bxkzcb** [comment]
可以的

**Comment by 981410121** [comment]
> 可以的

你方便发我一下你的参考一下吗，我添加了VTUAV的数据加载文件后，相关的配置都已经更改，不过在训练的时候一直卡着
![Uploading 123.png…]()
动不了
