### ISSUE TITLE
预训练相关问题

### ISSUE THREAD

**Issue by xiajianqiang** [RyanHTR/TBSI#6]
想请教一下作者，您在论文中提到使用了COCO, LaSOT, GOT-10k 以及TrackingNet等RGB目标跟踪数据集做预训练，请问您是使用了这些数据集的全部数据呢，还是仅仅使用了每个数据集的训练集部分，或者说您直接使用了OSTrack的预训练参数。

**Comment by RyanHTR** [comment]
您好，我们直接使用了OSTrack的预训练参数。
